name: Run Grype Vulnerability Scan

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate SBOM
    
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3
      
    - name: Get Vulnerabilities
      uses: anchore/scan-action@v3
      with:
        path: "."
        fail-build: false
        severity-cutoff: critical
      
