name: Run Microsoft SBOM Tool 

on: push

jobs:
  sbom:
    name: runner / elvis
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.4-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix do deps.get, deps.compile
      - name: sbom
        uses: red-shirts/action-mix-sbom@v1
