name: Sample with SBOM generation

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3
    - name: Generate SBOM
      run: |
        curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x sbom-tool
        sbom-tool generate -b . -bc . -pn Test -pv 1.0.0 -nsb https://sbom.mycompany.com -V Verbose >> ./sbom.csv
    
    - name: my-artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./sbom.csv
