name: Run Syft Scan

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate SBOM
    steps:
    - uses: anchore/sbom-action@v0
      continue-on-error: true
      with:
        path: https://github.com/${{ github.repository }}/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
